"""Create all system

Revision ID: 3145c94a39a5
Revises: 563d1cb3cd6b
Create Date: 2025-04-22 20:05:25.656600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3145c94a39a5'
down_revision: Union[str, None] = '563d1cb3cd6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('OPEN', 'REGIONAL', 'FEDERAL', name='competitionstype', native_enum=False), nullable=False),
    sa.Column('discipline', sa.Enum('PRODUCT', 'SECURITY', 'ALGORITHMIC', 'ROBOTICS', 'UAV', name='competitionsdiscipline', native_enum=False), nullable=False),
    sa.Column('date_to_create', sa.Date(), nullable=False),
    sa.Column('date_to_start', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('max_count_users', sa.Integer(), nullable=True),
    sa.Column('min_age_users', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('competitions_id', sa.Integer(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('FILLED', 'NEED_PLAYERS', name='commandstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['competitions_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('limitation_region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitions_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competitions_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_in_competitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitions_id', sa.Integer(), nullable=False),
    sa.Column('commands_id', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('сomment', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ON_MODERATION', 'REJECTED', 'FORMING', 'APPROVED', 'COMPLETED', name='commandincompetitionsstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['commands_id'], ['commands.id'], ),
    sa.ForeignKeyConstraint(['competitions_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_in_competitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commands_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commands_id'], ['commands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_in_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'WAITING_LEADER', 'MEMBER', 'DECLINED', name='usersincommandsstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_in_commands')
    op.drop_table('region_in_competitions')
    op.drop_table('command_in_competitions')
    op.drop_table('limitation_region')
    op.drop_table('commands')
    op.drop_table('user_region')
    op.drop_table('competitions')
    op.drop_table('region')
    # ### end Alembic commands ###
