"""Fix comment in TeamRequest models

Revision ID: 56350786bef0
Revises: 8b6b5e200076
Create Date: 2025-04-24 10:57:13.105402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56350786bef0'
down_revision: Union[str, None] = '8b6b5e200076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_request', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('team_request', 'сomment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_request', sa.Column('сomment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('team_request', 'comment')
    # ### end Alembic commands ###
