"""Add comment in UserInTeams

Revision ID: 76db34a998bb
Revises: cff921ea2372
Create Date: 2025-04-23 12:06:50.329212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76db34a998bb'
down_revision: Union[str, None] = 'cff921ea2372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_in_teams', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_in_teams', 'comment')
    # ### end Alembic commands ###
