"""Edit Users

Revision ID: ae2867119a1b
Revises: 400e3477299d
Create Date: 2025-04-21 18:46:11.906346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae2867119a1b'
down_revision: Union[str, None] = '400e3477299d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('FEDERATION', 'REGIONAL_REP', 'ATHLETE', name='userrole'),
               type_=sa.Enum('FEDERATION', 'REGIONAL_REP', 'ATHLETE', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('FEDERATION', 'REGIONAL_REP', 'ATHLETE', name='userrole', native_enum=False),
               type_=postgresql.ENUM('FEDERATION', 'REGIONAL_REP', 'ATHLETE', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
